language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install .

script:
  - cd tests
  - nosetests --with-coverage --cover-package=stile --with-doctest --cover-erase tests/test_binning.py tests/test_stile_utils.py

after_success:
  - coverage xml
  - codecov

deploy:
  provider: pypi
  user: msimet
  password:
    secure: secure_token
  on:
    tags: true
    branch: master
